version: "3.7"
services:
  db:
    image: mariadb:latest
    volumes:
      #마운트 작업 로컬 <-> 도커 컨테이너
      - "./db/data:/var/lib/mysql"
      - "./db/dump:/disk"
      - "./db/initdb.d:/docker-entrypoint-initdb.d"
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: Jhyuklim1!
      MYSQL_DATABASE: mysqldb
    ports:
      #포트포워딩 할 포트 설정
      - "33306:3306"
    restart: always
  ######################################
  # adminer : DB 관리 툴 
  ######################################
  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 58080:8080
  tomcat:
    image: tomcat:latest
    environment:
      - "JAVA_OPTS=-Dspring.profiles.active=dev"
    build:
      context: .
      #참조할 도커파일 명시
      dockerfile: Dockerfile-tomcat
    ports:
    #포트포워딩 할 포트 설정
      - "48080:8080"
    volumes:
      #마운트 작업 로컬 <-> 도커 컨테이너
      - ./lib/tomcat.shared.lib/:/usr/local/tomcat/shared/lib/
      - ./lib/tomcat.server.lib/:/usr/local/tomcat/server/lib/
      - ./lib/tomcat.webapps_crm.WEB-INF.lib/:/usr/local/tomcat/webapps_crm/ROOT/WEB-INF/lib/
      - ./tomcat/webapps_crm/ROOT/:/usr/local/tomcat/webapps_crm/ROOT/
    links:
      - db
    restart: always