version: '3.3'
services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    restart: always
    volumes:
      - ./Configs/Authelia:/config #change this to a shared folder on your system. DO NOT use a "volume"
    ports:
      - 9091:9091
    environment:
      - TZ=Asia/Seoul
