version: '3.3'
services:
  jenkins:
    ports:
        - '38080:8080'
        - '50000:50000'
    environment:
        TZ: "Asia/Seoul"
    container_name: jenkins
    restart: always
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    image: 'jenkins/jenkins:lts-jdk11'
