version: '3.9'
services:
  cosmos-server:
    image: 'azukaar/cosmos-server:latest'
    volumes:
      - '/var/lib/cosmos:/config'
      - '/:/mnt/host'
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: always
    hostname: cosmos-server
    container_name: cosmos-server
    ports:
      - '443:443'
      - '80:80'
