services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - 19090:9090
    volumes:
      - /DOCKER_NAS1/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
