global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds.
 
scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['192.168.0.104:9100'] 

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['192.168.0.104:9121']
      
  - job_name: 'kafka-exporter'
    scrape_interval: 15s
    scrape_timeout:  15s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['192.168.0.104:9308']
