version: '3.9'
services:
  dashy:
    image: 'lissy93/dashy:latest'
    restart: always
    container_name: my-dashboard
    volumes:
        - './my-conf.yml:/app/public/conf.yml'
    ports:
        - '8080:80'
