version: "3.7"
services:
  ######################################
  # adminer : DB 관리 툴 
  ######################################
  adminer:
    image: adminer
    #restart: always
    container_name: adminer
    ports:
      - 48080:8080
  tomcat:
    image: tomcat:latest
    environment:
      - "JAVA_OPTS=-Dspring.profiles.active=dev"
    build:
      context: .
      #참조할 도커파일 명시
      dockerfile: Dockerfile-tomcat
    ports:
    #포트포워딩 할 포트 설정
      - "58080:8080"
    volumes:
      #마운트 작업 로컬 <-> 도커 컨테이너
      #- ./lib/tomcat.shared.lib/:/usr/local/tomcat/shared/lib/
      #- ./lib/tomcat.server.lib/:/usr/local/tomcat/server/lib/
      - ./lib/tomcat/:/usr/local/tomcat/
