version: '3.3'
services:
    gitlab-ce:
        ports:
            - '18080:80'
            - '18822:22'
            - '18443:443'
        volumes:
            - '/var/run/docker.sock:/tmp/docker.sock:ro'
            - './config:/etc/gitlab'
            - './logs:/var/log/gitlab'
            - './data:/var/opt/gitlab'
        restart: 'unless-stopped'
        logging:
            options:
                max-size: 2g
        container_name: 'gitlab'
        environment:
            - 'GITLAB_OMNIBUS_CONFIG=nginx[''redirect_http_to_https''] = true;'
        image: 'gitlab/gitlab-ce:latest'