version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: windows
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
    environment:
      #VERSION: "win11"
      VERSION: "win10"
      #VERSION: "2025"
      #VERSION: "2022"
      #VERSION: "2019"
      RAM_SIZE: "12G"
      CPU_CORES: "6"
      DISK_SIZE: "150G"
      #VERSION: "https://example.com/win.iso"
    volumes:
      #- ./win11:/storage
      - ./win10:/storage
      #- ./server2025:/storage
      #- ./server2022:/storage
      #- ./server2019:/storage
