services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11" # 11l, 2025, 2022, 2019
      RAM_SIZE: "12G"
      CPU_CORES: "6"
      DISK_SIZE: "150G"
      USERNAME: "admin"
      PASSWORD: "admin"
      LANGUAGE: "Korean"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    volumes:
      #- /APP/windows/win11:/storage
      - /APP/windows/win10:/storage
      #- /APP/windows/server2025:/storage
      #- /APP/windows/server2022:/storage
      #- /APP/windows/server2019:/storage
#    networks:
#      vlan:
#        ipv4_address: 192.168.0.77

#networks:
#  vlan:
#    external: true
