services:
  node-stress-test:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-stress-test:latest
    container_name: node-stress-test
    restart: always
    ports:
      - "3010:3000"
      - "3011:3000"
# docker compose up -d --build
