apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: kubernetes
spec:
  hosts:
  - {name: m-k8s, address: 192.168.0.20, internalAddress: 192.168.0.20, privateKeyPath: "~/.ssh/id_rsa"}
  - {name: n1-k8s, address: 192.168.0.21, internalAddress: 192.168.0.21, privateKeyPath: "~/.ssh/id_rsa"}
  - {name: n2-k8s, address: 192.168.0.22, internalAddress: 192.168.0.22, privateKeyPath: "~/.ssh/id_rsa"}
  - {name: n3-k8s, address: 192.168.0.23, internalAddress: 192.168.0.23, privateKeyPath: "~/.ssh/id_rsa"}
  roleGroups:
    etcd:
    - m-k8s
    control-plane: 
    - m-k8s
    worker:
    - n1-k8s
    - n2-k8s
    - n3-k8s
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers 
    # internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v.1.22.12
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: 
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []
