version: '3.8'
services:
  kafka-monitor:
    image: yahoo/kafka-monitor:latest
    ports:
      - 8080:8080
    environment:
      - KAFKA_MANAGER_HTTP_USERNAME=admin
      - KAFKA_MANAGER_HTTP_PASSWORD=admin
      - KAFKA_MANAGER_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_MANAGER_KAFKA_BROKERS=kafka:9092
    depends_on:
      - kafka
      - zookeeper
    restart: always

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CREATE_TOPICS=test-topic:1:1
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - 2181:2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    restart: always
