version: '3'
services:
  redmine:
    image: redmine:latest
    container_name: redmine
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./redmine_data:/usr/src/redmine/files
    environment:
      - REDMINE_DB_MYSQL=192.168.0.163
      - REDMINE_DB_PORT=3306
      - REDMINE_DB_PASSWORD=root
      - REDMINE_DB_PASSWORD=mysql
      - REDMINE_DB_DATABASE=redmin
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: redmine_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=myrootpassword
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=myuserpassword
    volumes:
      - ./mysql_data:/var/lib/mysql
