version: "2.1"
services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./ntfy/cache/ntfy:/var/cache/ntfy
      - ./ntfy/ntfy:/etc/ntfy
    ports:
      - 8081:80
    restart: always
