gitlab-runner:
  container_name: gitlab-runner
  image: 'gitlab/gitlab-runner:latest'
  restart: unless-stopped
  volumes:
    - './config:/etc/gitlab-runner'
    - '/var/run/docker.sock:/var/run/docker.sock'
