version: '3'

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:2.9.22
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8081:81"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - ./client_body_temp:/client_body_temp
    environment:
      DB_MYSQL_HOST: db
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: npm
      DB_MYSQL_PASSWORD: npm
      DB_MYSQL_NAME: npm
    depends_on:
      - db

  db:
    image: jc21/mariadb-aria
    container_name: nginx-proxy-manager-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: npm
      MYSQL_DATABASE: npm
      MYSQL_USER: npm
      MYSQL_PASSWORD: npm
    volumes:
      - ./data/mysql:/var/lib/mysql

  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./data:/data
    depends_on:
      - nginx-proxy-manager
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"

networks:
  default:
    name: nginx-proxy-manager_default
    external: true
