version: '3.3'
services:
    confluence:
        volumes:
            - './data/your-confluence-home:/var/atlassian/application-data/confluence'
        container_name: confluence
        ports:
            - '8090:8090'
            - '8091:8091'
        image: atlassian/confluence
