version: "3.3"
services:
  open-webui:
    ports:
      - 3000:8080
    environment:
      - OLLAMA_BASE_URL=https://webui.itapi.org
    volumes:
      - /APP/open-webui:/app/backend/data
    container_name: open-webui
    restart: always
    image: ghcr.io/open-webui/open-webui:main
