version: '3'
services:
  owncloud:
    image: owncloud:latest
    container_name: owncloud
    restart: always
    ports:
      - '8080:80'
    environment:
      - OWNCLOUD_DOMAIN=localhost:8080
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=ownclouduser
      - OWNCLOUD_DB_PASSWORD=owncloudpassword
      - OWNCLOUD_DB_HOST=db
    volumes:
      - ./owncloud_data:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: owncloud_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=myrootpassword
      - MYSQL_DATABASE=owncloud
      - MYSQL_USER=ownclouduser
      - MYSQL_PASSWORD=owncloudpassword
    volumes:
      - ./mysql_data:/var/lib/mysql
