version: '3.3'
services:
    nexus3:
        ports:
            - '28180:80'
            - '25000:5000'
            - '28081:8081'
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./nexus-data:/nexus-data
        restart: unless-stopped
        logging:
            options:
                max-size: 1g
        container_name: nexus
        image: sonatype/nexus3

#chown -R 200 ./nexus-data
