# https://github.com/eftechcombr/glpi.git
services:
  mariadb: 
    image: mariadb:11.4
    restart: unless-stopped
    volumes: 
      - /APP/glpi/mariadb-glpi-volume:/var/lib/mysql:rw
    env_file: ./.env 
    ports: 
      - 3306:3306

  mariadb-timezone: 
    image: mariadb:11.4
    restart: on-failure
    env_file: ./.env
    depends_on:
      - mariadb
    command: mariadb -h $MARIADB_HOST -u root -p$MARIADB_ROOT_PASSWORD -e "GRANT SELECT ON \`mysql\`.\`time_zone_name\` TO 'glpi'@'%'; FLUSH PRIVILEGES;"

  glpi-db-install:
    image: eftechcombr/glpi:php-fpm-10.0.17
    restart: on-failure 
    env_file: ./.env
    volumes: 
      - /APP/glpi/glpi-marketplace:/var/www/html/marketplace:rw
      - /APP/glpi/glpi-files:/var/lib/glpi:rw
      - /APP/glpi/glpi-etc:/etc/glpi:rw    
    depends_on: 
      - mariadb
    command: 
      - /usr/local/bin/glpi-db-install.sh

  glpi-verify-dir: 
    image: eftechcombr/glpi:php-fpm-10.0.17
    restart: on-failure
    volumes: 
      - /APP/glpi/glpi-marketplace:/var/www/html/marketplace:rw
      - /APP/glpi/glpi-files:/var/lib/glpi:rw
      - /APP/glpi/glpi-etc:/etc/glpi:rw
    env_file: ./.env
    depends_on: 
      - glpi-db-install
    command: 
      - /usr/local/bin/glpi-verify-dir.sh

  glpi-db-configure: 
    image: eftechcombr/glpi:php-fpm-10.0.17
    restart: on-failure
    volumes: 
      - /APP/glpi/glpi-marketplace:/var/www/html/marketplace:rw
      - /APP/glpi/glpi-files:/var/lib/glpi:rw
      - /APP/glpi/glpi-etc:/etc/glpi:rw
    env_file: ./.env
    depends_on: 
      - glpi-verify-dir
    command: 
      - /usr/local/bin/glpi-db-configure.sh

  php: 
    image: eftechcombr/glpi:php-fpm-10.0.17
    restart: unless-stopped
    volumes: 
      - /APP/glpi/glpi-marketplace:/var/www/html/marketplace:rw
      - /APP/glpi/glpi-files:/var/lib/glpi:rw
      - /APP/glpi/glpi-etc:/etc/glpi:rw
    env_file: ./.env
    depends_on: 
      - mariadb
      - glpi-db-install
      - glpi-db-configure
      - glpi-verify-dir
    ports: 
      - "9000:9000"

  nginx: 
    image: eftechcombr/glpi:nginx-10.0.17
    restart: unless-stopped
    ports: 
      - "8080:80"
    depends_on: 
      - php

volumes: 
  glpi-marketplace:
  glpi-files:
  glpi-etc:
  glpi-install:
  mariadb-glpi-volume: 

# networks: 
#   glpi-frontend: 
#   glpi-backend:
