version: '3.9'
services:
  meilisearch:
    image: 'getmeili/meilisearch:v1.10'
    volumes:
      - '/APP/meilisearch/meili_data:/meili_data'
    environment:
        - MEILI_ENV=development
    ports:
      - '7700:7700'
    tty: true
    stdin_open: true
