version: "3.7"
services:
  synochat:
    image: noname09/synochat_ds
    container_name: synochat
    volumes:
      #마운트 작업 로컬 <-> 도커 컨테이너
      - "./data:/config"
    environment:
      - MY_ID=modenaf360
      - MY_PW=1234
      - MY_URL=http://146.56.47.118:24287
      - TZ:Asia/Seoul
    ports:
      #포트포워딩 할 포트 설정
      - "24287:4287"
    #restart: always