apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv4-nas-ocp-pv-log
spec:
  capacity:
    storage: 10Gi # 원하는 스토리지 용량으로 변경
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.0.98
    path: /pv4-zfs/pv4-nas-ocp/ocp-logs
