services:
  upsnap:
    image: ghcr.io/seriousm4x/upsnap:4
    container_name: UpSnap
    mem_limit: 512m 
    cpu_shares: 768
    healthcheck:
     test: curl -f http://localhost:80/ || exit 1
    network_mode: host
    restart: always
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /volume1/docker/upsnap:/app/pb_data:rw
