version: '3.9'
services:
  cloudbeaver:
    image: 'dbeaver/cloudbeaver:latest'
    restart: always
    volumes:
      - '/volume1/docker/cloudbeaver:/opt/cloudbeaver/workspace'
    ports:
      - '5495:8978'
    container_name: cloudbeaver
