version: '3.9'
services:
  strapi:
    image: strapi/strapi
    volumes:
      - '/APP/strapi/itapi:/srv/app'
    ports:
      - '1337:1337'
    environment:
      - DATABASE_PASSWORD=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PORT=15432
      - DATABASE_HOST=itapi.org
      - DATABASE_NAME=strapi
      - DATABASE_CLIENT=postgres
    tty: true
    stdin_open: true
