version: '3.1'

services:

  yourls:
    container_name: 'dalso-yourls'
    image: yourls
    restart: always
    ports:
      - 8080:80
    environment:
      YOURLS_DB_PASS: admin
      YOURLS_SITE: http://192.168.0.43
      YOURLS_USER: admin
      YOURLS_PASS: admin

  mysql:
    image: mysql:latest
    container_name: 'dalso-yourls-mysql'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
