---
services:
  snipe-it:
    image: lscr.io/linuxserver/snipe-it:latest
    container_name: snipe-it
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Seoul
      - APP_KEY=
      - APP_URL=http://192.168.0.120:8280
      - MYSQL_PORT_3306_TCP_ADDR=itapi.org
      - MYSQL_PORT_3306_TCP_PORT=13306
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=mysql
      - APP_DEBUG=false #optional
      - APP_ENV=production #optional
      - APP_FORCE_TLS=false #optional
      - APP_LOCALE= #optional
      - MAIL_PORT_587_TCP_ADDR= #optional
      - MAIL_PORT_587_TCP_PORT= #optional
      - MAIL_ENV_FROM_ADDR= #optional
      - MAIL_ENV_FROM_NAME= #optional
      - MAIL_ENV_ENCRYPTION= #optional
      - MAIL_ENV_USERNAME= #optional
      - MAIL_ENV_PASSWORD= #optional
    volumes:
      - /path/to/snipe-it/data:/config
    ports:
      - 8280:80
    restart: unless-stopped
