version: "3"
services:
  snipeit:
    image: linuxserver/snipe-it:latest
    container_name: snipe-it
    restart: always
  network_mode: bridge
    external_links:
     - mariadb:mariadb      
    volumes:
      - ./config:/config
    environment:
      - NGINX_APP_URL=(리버스 프록시 사용시 도메인 주소)
      - MYSQL_PORT_3306_TCP_ADDR=mariadb
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=snipeit
      - MYSQL_USER=snipeit
      - MYSQL_PASSWORD=snipeit
      - PGID=1000
      - PUID=1000
      - APP_TIMEZONE=Asia/Seoul
      - APP_LOCALE=ko
    ports:
      - "8080:80"