#!/bin/bash

# --- NFS 서버 및 마운트 경로 설정 ---
# NFS 서버의 IP 주소입니다.
NFS_SERVER="192.168.0.101"

# 마운트할 백업 대상 목록 (1부터 4까지 반복)
for i in {1..4}
do
  LOCAL_MOUNT_POINT="/APP/PVE${i}-BACKUP"
  REMOTE_NFS_SHARE="/pv2-zfs/pv2-backup/PVE${i}-BACKUP"

  echo "PVE${i} 마운트 작업을 시작합니다..."

  # 로컬 마운트 포인트 디렉토리가 없으면 생성합니다.
  if [ ! -d "$LOCAL_MOUNT_POINT" ]; then
    echo "  디렉토리 $LOCAL_MOUNT_POINT 가 존재하지 않아 생성합니다."
    mkdir -p "$LOCAL_MOUNT_POINT"
  fi

  # NFS 마운트를 실행합니다.
  # -t nfs: 파일 시스템 타입을 NFS로 지정합니다.
  # -o vers=4.1,hard,intr: 마운트 옵션으로 NFS 버전 4.1, 하드 마운트, 인터럽트 허용을 사용합니다.
  mount -t nfs -o vers=4.1,hard,intr "${NFS_SERVER}:${REMOTE_NFS_SHARE}" "${LOCAL_MOUNT_POINT}"

  # 마운트 성공 여부를 확인합니다.
  if [ $? -eq 0 ]; then
    echo "  성공적으로 마운트되었습니다: ${NFS_SERVER}:${REMOTE_NFS_SHARE} -> ${LOCAL_MOUNT_POINT}"
  else
    echo "  마운트에 실패했습니다: ${NFS_SERVER}:${REMOTE_NFS_SHARE}"
  fi
done

echo ""
echo "---"
echo "모든 마운트 작업이 완료되었습니다. 현재 마운트 상태입니다."
# 마운트된 디스크 목록 중 /APP/PVE로 시작하는 항목만 필터링하여 표시합니다.
df -h | grep "/APP/PVE"
echo "---"

# --- Proxmox Datastore 설정 파일 생성 스크립트 ---

# 설정 파일 경로를 정의합니다.
CONFIG_FILE="/etc/proxmox-backup/datastore.cfg"

echo "Proxmox Datastore 설정 파일(${CONFIG_FILE})을 생성합니다..."

# 기존 파일이 있으면 덮어씁니다.
echo "# Auto-generated by create_datastore_config.sh" > "$CONFIG_FILE"

# 1부터 4까지 반복하여 각 데이터스토어를 설정 파일에 추가합니다.
for i in {1..4}
do
  DATASTORE_NAME="PVE${i}-BACKUP"
  DATASTORE_PATH="/APP/${DATASTORE_NAME}"

  echo "  - ${DATASTORE_NAME} 데이터스토어 설정 추가 중..."
  
  # 데이터스토어 설정을 파일에 추가합니다.
  cat << EOF >> "$CONFIG_FILE"

datastore: ${DATASTORE_NAME}
        comment 
        gc-schedule daily
        notification-mode notification-system
        path ${DATASTORE_PATH}
EOF
done

echo ""
echo "---"
echo "Datastore 설정 파일 생성이 완료되었습니다. 파일 내용:"
echo "---"

# 생성된 파일의 내용을 출력합니다.
cat "$CONFIG_FILE"
echo "---"
