version: "3.7"
services:
  ######################################
  # adminer : DB 관리 툴 
  ######################################
  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 48080:8080
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment: 
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=myssql
      - TZ=Asia/Seoul
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
     - 8180:80
    environment:
     - PMA_HOSTS=192.168.0.129
     - PMA_PORTS=3306
     - MYSQL_ROOT_PASSWORD=mysql
