version: '3.9'
services:
    # kong api-gateway
    kong:
        container_name: kong
        image: 'kong:latest'
        restart: always
        ports:
            - '8444:8444'
            - '8001:8001'
            - '8443:8443'
            - '8000:8000'
        environment:
            - 'KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl'
            - KONG_ADMIN_ERROR_LOG=/dev/stderr
            - KONG_PROXY_ERROR_LOG=/dev/stderr
            - KONG_ADMIN_ACCESS_LOG=/dev/stdout
            - KONG_PROXY_ACCESS_LOG=/dev/stdout
            - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
            - KONG_DATABASE=off
        volumes:
            - './kong-vol:/usr/local/kong/declarative'
        
    # kong api-gateway admin web gui
    konga:
        container_name: konga
        image: pantsel/konga
        restart: always
        ports:
            - '1337:1337'
        environment:
            - NODE_ENV=production
        volumes:
            - './kongadata:/app/kongadata'
