services:
  piper:
    image: reallibre/piper-http:latest
    container_name: piper
    ports:
      - "5000:5000"  # 이 이미지는 기본적으로 5000번 포트를 사용합니다
    environment:
      - PIPER_VOICE=ko_KR-sun-medium
    volumes:
      - ./piper-config:/app/models # 모델 파일 저장 경로
    restart: unless-stopped
