version: '2.1'
services:
  piwigo:
    image: lscr.io/linuxserver/piwigo:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./appdata/config:/config
      - ./appdata/gallery:/gallery
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Seoul
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=piwigo
      - MYSQL_USER=piwigo
      - MYSQL_PASSWORD=piwigo
      - MYSQL_ROOT_PASSWORD=piwigo
    volumes:
      - ./db:/var/lib/mysql
