---
- name: Check OS Version to Target Server
  hosts: all
  tasks:
  - name: Check OS Version
    register: result
    shell: cat /etc/keepalived/keepalived.conf
  - name: update APT
    register: result
    shell: apt update
  - debug:
      msg: "{{ result.stdout }}"
