version: '3'

services:
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
     - 8180:80
    volumes:
     - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config/config.user.inc.php
    environment:
     - PMA_HOSTS=127.0.0.1
     - PMA_PORTS=3306
     - MYSQL_ROOT_PASSWORD=mysql
