version: '2'

services:
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    networks:
     - UDN_Database
    ports:
     - 10240:80
    volumes:
     - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config/config.user.inc.php
    environment:
     - PMA_HOSTS=mysql
     - PMA_PORTS=33061

networks:
  UDN_Database:
    external:
      name: UDN_Database
  UDN_Service:
    external:
      name: UDN_Service
