version: '3.3'
services:
    phpmyadmin:
        container_name: phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            #- PMA_HOST=dbhost
            #- PMA_PORTS=3306
        ports:
            - '8080:80'
        image: phpmyadmin
        #links:
        #    - 'mysql_db_server:db'
        #volumes:
        #    - '/some/local/directory/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php'
