version: '3'

services:
  emby:
    image: emby/embyserver:latest
    container_name: emby
    restart: always
    ports:
      - "8096:8096"
      - "8920:8920"
    volumes:
      - "./path/to/media:/mnt/media"
      - "./path/to/config:/config"
#    environment:
#      - UID=<your_uid>
#      - GID=<your_gid>
