services:
  intellissh:
    image: clusterzx/intellissh:latest
    container_name: intellissh
    ports:
      - 8280:3000
    volumes:
      # Mount for persistent backend data (SQLite DB, session info, etc.)
      - /APP/intellissh/data:/app/server/data
    restart: always
