version: '3.9'
services:
  linuxserver:
    command: 'Before you paste the code above in'
    image: ghcr.io/linuxserver/wireshark
    restart: always
    volumes:
      - '/APP/wireshark:/config'
    environment:
      - PASSWORD=1q2w3e4r5t^Y
      - CUSTOM_USER=admin
      - TZ=Asia/Seoul
      - PGID=100
      - PUID=1026
    ports:
      - '3124:3000'
    cap_add:
      - NET_ADMIN
    container_name: wireshark
