version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    command: --lower_case_table_names=1
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 23306:3306
    environment: 
      - MYSQL_DATABASE=mysql_test
      - MYSQL_ROOT_PASSWORD=Jhyuklim1!
      - TZ=Asia/Seoul
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
#    user: "${USER_ID}:${GROUP_ID}"
