version: '3.9'
services:
  dockge:
    image: 'louislam/dockge:1'
    restart: always
    environment:
      - DOCKGE_STACKS_DIR=/volume1/docker/dockge/stacks
    volumes:
      - '/APP/dockge/data:/app/data'
      - '/APP/dockge/stacks:/volume1/docker/dockge/stacks'
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - '5571:5001'
    container_name: Dockge
