#!/bin/bash

RESOLV_CONF="/etc/resolv.conf"

cat <<EOF >> $RESOLV_CONF

#Generated by NetworkManager
search ocp4.okd.io
nameserver 192.168.0.69    # 내부 DNS (우선)
nameserver 168.126.63.1    # 외부 DNS
EOF

echo "DNS configuration has been added to $RESOLV_CONF"

# named 서버 재기동
systemctl enable named
systemctl start named

# DNS 확인
nslookup ocp.ocp4.okd.io localhost
