version: '3.7'

services:
  burrow:
    image: punksolid/burrow:latest
    container_name: burrow
    ports:
      - 8000:8000
    environment:
      - BURROW_CONFIGFILE=/etc/burrow/burrow.toml
    volumes:
      - ./burrow.toml:/etc/burrow/burrow.toml
    depends_on:
      - kafka

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    hostname: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_CREATE_TOPICS=test:1:1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181
