version: '3.3'
services:
  uptime-kuma:
    restart: always
    ports:
        - '3001:3001'
    volumes:
        - './uptime-kuma:/app/data'
    container_name: uptime-kuma
    image: 'louislam/uptime-kuma:1'

# for reverse-proxy setting
# https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy
