version: '3'
services:
  code-server:
    container_name: vscode
    image: codercom/code-server:latest
    ports:
      - 8080:8080
    volumes:
      - ./data:/home/coder
    environment:
      - PASSWORD=admin
    restart: always
