# compose 파일 버전
version: "3"
services: 
  # 서비스명 
  # Redis Cluster 설정
  redis-cluster:
    # 사용할 이미지
    image: redis:latest
    # 컨테이너명 설정
    container_name: redis-cluster
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "6001:6001"
      - "6002:6002"
      - "6003:6003"
      - "6004:6004"
      - "6005:6005"
      - "6006:6006"
      - "6007:6007"
      - "6008:6008"
      - "6009:6009"
    # 환경 변수 설정
    volumes:
      - ./config/redis/redis-cluster.conf:/usr/local/etc/redis.conf
    # 명령어 설정  
    command: redis-server /usr/local/etc/redis.conf
  
  # Redis Node1 설정  
  redis-node1:
    network_mode: "service:redis-cluster"
    image: redis:latest
    container_name: redis-node1
    volumes:
      - ./redis-node1.conf:/usr/local/etc/redis.conf
    command: redis-server /usr/local/etc/redis.conf
  
  # Redis Node2 설정    
  redis-node2:
    network_mode: "service:redis-cluster"
    image: redis:latest
    container_name: redis-node2
    volumes:
      - ./redis-node2.conf:/usr/local/etc/redis.conf
    command: redis-server /usr/local/etc/redis.conf

  # Redis Node3 설정  
  redis-node3:
    network_mode: "service:redis-cluster"
    image: redis:latest
    container_name: redis-node3
    volumes:
      - ./redis-node3.conf:/usr/local/etc/redis.conf
    command: redis-server /usr/local/etc/redis.conf
  
  # Redis Node4 설정  
  redis-node4:
    network_mode: "service:redis-cluster"
    image: redis:latest
    container_name: redis-node4
    volumes:
      - ./redis-node4.conf:/usr/local/etc/redis.conf
    command: redis-server /usr/local/etc/redis.conf
  
  # Redis Node5 설정    
  redis-node5:
    network_mode: "service:redis-cluster"
    image: redis:latest
    container_name: redis-node5
    volumes:
      - ./redis-node5.conf:/usr/local/etc/redis.conf
    command: redis-server /usr/local/etc/redis.conf

  # Redis Node6 설정  
  redis-node6:
    network_mode: "service:redis-cluster"
    image: redis:latest
    container_name: redis-node6
    volumes:
      - ./redis-node6.conf:/usr/local/etc/redis.conf
    command: redis-server /usr/local/etc/redis.conf
  
  # Redis Node7 설정  
  redis-node7:
    network_mode: "service:redis-cluster"
    image: redis:latest
    container_name: redis-node7
    volumes:
      - ./redis-node7.conf:/usr/local/etc/redis.conf
    command: redis-server /usr/local/etc/redis.conf
  
  # Redis Node8 설정    
  redis-node8:
    network_mode: "service:redis-cluster"
    image: redis:latest
    container_name: redis-node8
    volumes:
      - ./redis-node8.conf:/usr/local/etc/redis.conf
    command: redis-server /usr/local/etc/redis.conf

  # Redis Node9 설정  
  redis-node9:
    network_mode: "service:redis-cluster"
    image: redis:latest
    container_name: redis-node9
    volumes:
      - ./redis-node9.conf:/usr/local/etc/redis.conf
    command: redis-server /usr/local/etc/redis.conf

  # Redis Cluster Entry 설정  
  redis-cluster-entry:
    network_mode: "service:redis-cluster"
    image: redis:latest
    container_name: redis-cluster-entry
    command: redis-cli --cluster create 127.0.0.1:6001 127.0.0.1:6002 127.0.0.1:6003 127.0.0.1:6004 127.0.0.1:6005 127.0.0.1:6006 127.0.0.1:6007 127.0.0.1:6008 127.0.0.1:6009 --cluster-yes
    depends_on:
      - redis-cluster
      - redis-node1
      - redis-node2
      - redis-node3
      - redis-node4
      - redis-node5
      - redis-node6
      - redis-node7
      - redis-node8
      - redis-node9

  # P3X Redis UI 설정
  registry:
    image: patrikx3/p3x-redis-ui:latest
    restart: always
    container_name: p3x-redis-ui
    ports:
      - "7843:7843"
    volumes:
      - ./settings:/settings

  redis-stat:
    image: insready/redis-stat:latest
    container_name: redis-stat
    restart: always
    ports:
      - 8080:63790
    links:
      - redis-cluster:redis-cluster
    command: --server redis-cluster:6001 redis-cluster:6002 redis-cluster:6003 redis-cluster:6004 redis-cluster:6005 redis-cluster:6006 redis-cluster:6007 redis-cluster:6008 redis-cluster:6009
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
      - redis-node4
      - redis-node5
      - redis-node6
      - redis-node7
      - redis-node8
      - redis-node9
