name: Mirror to GitLab

on:
  push:
    branches: [ "main" ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to Home Server GitLab
        run: |
          # 1. 원격 저장소 추가 (토큰 방식 유지)
          git remote add gitlab https://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_PASSWORD }}@gitlab.itapi.org/home-server/github-mirror.git
          
          # 2. Cloudflare를 통과하기 위한 비밀 헤더(x-cf-bypass)를 추가하여 강제 푸시
          git -c http.extraHeader="x-cf-bypass: ${{ secrets.GITLAB_BY_PASS }}" push gitlab --mirror
