name: Mirror to GitLab

on:
  push:
    branches: [ "main" ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to Home Server GitLab
        run: |
          git remote add gitlab https://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_PASSWORD }}@gitlab.itapi.org/home-server/github-mirror.git
          git push gitlab --mirror
