version: '3.3'
services:
    server:
        container_name: vaultwarden
        volumes:
            - '/vw-data/:/data/'
        ports:
            - '80:80'
        image: 'vaultwarden/server:latest'

#https://github.com/dani-garcia/vaultwarden
